name: Generate Snake Animation

on:
  # 每12小时自动运行一次
  schedule:
    - cron: "0 */12 * * *"
  
  # 允许手动触发
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # 生成贪吃蛇动画，基于您的 GitHub 贡献图
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: hviwen
          outputs: |
            assets/github-snake.svg
            assets/github-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # 推送生成的文件到仓库
      - name: Push snake svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: master
          build_dir: assets
          keep_history: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}